monitor.alsa.rules = [
  {
    matches = [
      {
        # Match all ALSA/Audio streams
        node.name = "~alsa_(output|input).*"
      }
    ]
    actions = {
      update-props = {
        # Force-suspend the node after 2 seconds of silence (default is 5)
        session.suspend-on-idle-timeout = 2
      }
    }
  }
]