[config]
mode = "dark"
type = "scheme-tonal-spot"
prefer = "less-saturation"
contrast = 0.25
base16_backend = "wal"

# [templates.sequences]
# input_path="~/.config/noctalia/templates/wallpaper-path.txt"
# output_path="/tmp/wallpaper-path.txt"
# post_hook = "WALLPATH=$(cat /tmp/wallpaper-path.txt) && $HOME/.local/bin/wal --cols16 darken --backend haishoku -n -i \"$WALLPATH\""

[templates.hyprcolors]
input_path="~/.config/noctalia/templates/hyprcolors.lua"
output_path="~/.config/hypr/hyprcolors.lua"

[templates.mangocolors]
input_path="~/.config/noctalia/templates/mangocolors.conf"
output_path="~/.config/mango/mangocolors.conf"

[templates.rofi]
input_path="~/.config/noctalia/templates/rofi-colors.rasi"
output_path="~/.config/rofi/noctalia.rasi"

[templates.gtk3]
input_path = "~/.config/noctalia/templates/gtk3-colors.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/.config/noctalia/templates/gtk4-colors.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.kvantum1]
input_path = "~/.config/noctalia/templates/kvantum-colors.kvconfig"
output_path = "~/.config/Kvantum/noctalia/noctalia.kvconfig"

[templates.kvantum2]
input_path = "~/.config/noctalia/templates/kvantum-colors.svg"
output_path = "~/.config/Kvantum/noctalia/noctalia.svg"
