format="""
$all
"""

[username]
disabled=false

[hostname]
disabled=false

[localip]
disabled=false

[shlvl]
disabled=false

[singularity]
disabled=false

[kubernetes]
disabled=false

[directory]
disabled=false

[vcsh]
disabled=false

[fossil_branch]
disabled=false

[fossil_metrics]
disabled=false

[git_branch]
disabled=false

[git_commit]
disabled=false

[git_state]
disabled=false

[git_metrics]
disabled=false

[git_status]
disabled=false

[hg_branch]
disabled=false

[pijul_channel]
disabled=false

[docker_context]
disabled=false

[package]
disabled=false

[bun]
disabled=false

[c]
disabled=false

[cmake]
disabled=false

[cobol]
disabled=false

[daml]
disabled=false

[dart]
disabled=false

[deno]
disabled=false

[dotnet]
disabled=false

[elixir]
disabled=false

[elm]
disabled=false

[erlang]
disabled=false

[fennel]
disabled=false

[gleam]
disabled=false

[golang]
disabled=false

[guix_shell]
disabled=false

[haskell]
disabled=false

[haxe]
disabled=false

[helm]
disabled=false

[java]
disabled=false

[julia]
disabled=false

[kotlin]
disabled=false

[gradle]
disabled=false

[lua]
disabled=false

[nim]
disabled=false

[nodejs]
disabled=false

[ocaml]
disabled=false

[opa]
disabled=false

[perl]
disabled=false

[php]
disabled=false

[pulumi]
disabled=false

[purescript]
disabled=false

[python]
disabled=false

[quarto]
disabled=false

[raku]
disabled=false

[rlang]
disabled=false

[red]
disabled=false

[ruby]
disabled=false

[rust]
disabled=false

[scala]
disabled=false

[solidity]
disabled=false

[swift]
disabled=false

[terraform]
disabled=false

[typst]
disabled=false

[vlang]
disabled=false

[vagrant]
disabled=false

[zig]
disabled=false

[buf]
disabled=false

[nix_shell]
disabled=false

[conda]
disabled=false

[meson]
disabled=false

[spack]
disabled=false

[memory_usage]
disabled=false

[openstack]
disabled=false

[nats]
disabled=false

[direnv]
disabled=false

[crystal]
disabled=false

[sudo]
disabled=false

[cmd_duration]
disabled=false

[line_break]
disabled=false

[jobs]
disabled=false

[battery]
disabled=false

[time]
disabled=false

[status]
disabled=false

[os]
disabled = false
style = "bg:black fg:white"
format="$symbol "

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[container]
disabled=false

[shell]
disabled = false

[character]
success_symbol = "[ ✓ ](bold green)"
error_symbol = "[ ✗ ](bold red)"
