general {
    lock_cmd = qs -c noctalia-shell ipc call lockScreen lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener { #
    timeout = 180 # in seconds
    on-timeout = brightnessctl -s set 5
    on-resume = brightnessctl -r
}

listener { # lock
  timeout = 240
  on-timeout = loginctl lock-session
}

listener {
  timeout = 300
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener { # sleep
	timeout = 360
	on-timeout = systemctl suspend
}